### ISSUE TITLE
I can't toggle console at any server.

### ISSUE THREAD

**Issue by EndreEndi** [WindowsGSM/WindowsGSM#11]
As the title says.

**Comment by BattlefieldDuck** [comment]
Which game server?

**Comment by EndreEndi** [comment]
CSGO

**Comment by BattlefieldDuck** [comment]
![csgoconsole](https://user-images.githubusercontent.com/29337428/74379418-ba51d080-4e22-11ea-986c-d613867b0056.png)
The server console is here

**Comment by EndreEndi** [comment]
Yes, but I'm limited in lines, and I can't scroll up to much, and I want the "normal" console.

**Comment by EndreEndi** [comment]
I mean why the "Toggle Console" button doesn't work anymore? It was pretty helpful. For me.

**Comment by BattlefieldDuck** [comment]
I see your point, I will remake that in the next release

**Comment by EndreEndi** [comment]
Thank you very much.

**Comment by EndreEndi** [comment]
Thank you!
