### ISSUE TITLE
Problem executing a command on the console!

### ISSUE THREAD

**Issue by MihailHavenT** [WindowsGSM/WindowsGSM#114]
There is a problem with executing a command on the integrated console on the WindowsGSM program, on the dedicated server of Unturned... I don't know if it's something normal or I'm wrong!

[CLICK HERE!](https://ibb.co/rFRsfmH)

**Comment by BattlefieldDuck** [comment]
Just tested on the Unturned server, redirect standard doesn't work on embed console, you need to turn off the embed console if you want to input the commands. Thank you.
