### ISSUE TITLE
[Discussion] Standard Input Method

### ISSUE THREAD

**Issue by laper32** [WindowsGSM/WindowsGSM#116]
As you should know, to input message from somewhere to the console, different game has different method.
For now on, we can summary these methods:
```cs
Process.StandardInput.WriteLine();
Win32API.PostMessage();
```
Is there any other possible methods?

**Comment by BattlefieldDuck** [comment]
For console application, 
```cs
Process.StandardInput.WriteLine(); // Redirect Standard Input
Win32API.PostMessage(); // Send message to windowed console using process.MainWindowHandle
PseudoConsole.WriteLine(); // Start the console with conpty and write line
```

For windowed application, 
```cs
Process.StandardInput.WriteLine(); // Redirect Standard Input (Not always work)
Win32API.PostMessage(); // Send message to windowed console using process.MainWindowHandle
```

**Comment by laper32** [comment]
> For console application,
> 
> ```cs
> Process.StandardInput.WriteLine(); // Redirect Standard Input
> Win32API.PostMessage(); // Send message to windowed console using process.MainWindowHandle
> PseudoConsole.WriteLine(); // Start the console with conpty and write line
> ```
> 
> For windowed application,
> 
> ```cs
> Process.StandardInput.WriteLine(); // Redirect Standard Input (Not always work)
> Win32API.PostMessage(); // Send message to windowed console using process.MainWindowHandle
> ```

For standard_input.writeln() not working: srcds/hlds/... (Valve's dedicated server).
Assumption: [https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/dedicated/conproc.cpp#L228](url)

**Comment by BattlefieldDuck** [comment]
srcds.exe is actually a windowed application. 🙃

**Comment by BattlefieldDuck** [comment]
For more info about srcds, you may check this https://forums.alliedmods.net/showthread.php?t=287902
It is possible to use `-HFILE -HPARENT -HCHILD` to get the output and input? You may investigate it.

**Comment by laper32** [comment]
late response: Doesnt found anything useful information about -HFILE -HPARENT -HCHILD, looks like they are unrelated to stdin.
