### ISSUE TITLE
Team Fortress 2 doesn't update latest version. 

### ISSUE THREAD

**Issue by mrnoahfink** [WindowsGSM/WindowsGSM#117]
**Describe the bug**
Since the TF2 update was released, it doesn't shut down and update automatically, I have to manually update myself, and an error pop-up. 

**To Reproduce**
1. Go to - Click any TF2 server
2. Click on - Actions, Update tab then press Update
-------------------------------------
( As the log shows it did update, but really it doesn't somehow)

[03/28/2022-21:29:00][#2] Action: Update
[03/28/2022-21:29:09][#3] Action: Update
[03/28/2022-21:29:15][#4] Action: Update
[03/28/2022-21:29:19][#2] Checking: Version (7975938) => (8453225)
[03/28/2022-21:29:21][#3] Checking: Version (7975938) => (8453225)
[03/28/2022-21:29:28][#3] Server: Updated (8453225)
[03/28/2022-21:29:39][#2] Server: Updated (8453225)
[03/28/2022-21:29:43][#4] Checking: Version (7975938) => (8453225)
[03/28/2022-21:29:50][#4] Server: Updated (8453225)

Here Actually showing in cmds
![Screenshot 2022-03-28 223630](https://user-images.githubusercontent.com/66857858/160528141-59659ec5-6e80-4db0-8b98-fb92e02d9c46.png)

**Expected behavior**
Server Verison updates correctly one, and force that rightfully verison.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition
 - Version: - 21h1

**Comment by mrnoahfink** [comment]
After creating a new folder on the desktop and transferring to that folder. Here Error now. 

![Screenshot 2022-03-28 230619](https://user-images.githubusercontent.com/66857858/160531259-e904264e-e8bc-4159-81df-8bdd8de08eef.png)

**Comment by BattlefieldDuck** [comment]
Thanks for the report, it should be steamcmd `force_install_dir` issue. Will be fix in the next release.

**Comment by mrnoahfink** [comment]
Can confirm on version 1.23.0 fixed the problem! Thank you so much BattlefieldDuck working on this project!
