### ISSUE TITLE
Rust Server Hardcoded Default Params

### ISSUE THREAD

**Issue by QuintonAjStevens** [WindowsGSM/WindowsGSM#118]
Trying to run a Rust server, and some parameters are being launched as default. For example, it loads these parameters with no way to change them: "+server.seed" "689777" "+server.worldsize" "3000"

I added the +server.seed and +server.worldsize parameters with their own values but the server takes the first parameters and ignores any duplicate parameters.

I don't see any obvious way to change this. Is everyone using WindowsGSM running the same Rust seed/world?

1. Go to launch a Rust server after adding the custom parameters of your choice.
2. Launches with default parameters that are unchangeable. 

Expected Behavior:
I would expect these parameters to either be options in the config, or not have a hard-coded default so that I can set them using additional params. 

Details:
I've pasted details with some info changed (IPs, names, etc) and this is my "Server Start Param" section for Rust server: -batchmode +server.hostname SERVERNAMEHERE +server.seed 6834 +server.worldsize 4000 +server.identity SERVERIDENTITYHERE

When I check the server.log, it shows it's attempting to launch with these parameters: "-nographics" "-batchmode" "-silent-crashes" "+server.hostname" "Rust" "+server.ip" "192.168.1.XXX" "+server.port" "28015" "+server.level" "Procedural Map" "+server.maxplayers" "6" "+rcon.ip" "0.0.0.0" "+rcon.port" "28015" "+rcon.password" "******" "+rcon.web" "1" "+server.tickrate" "10" "+server.description" "Rust Dedicated Server - Managed by WindowsGSM" "+server.url" "https://github.com/WindowsGSM/WindowsGSM" "+server.headerimage" "" "+server.identity" "server1" "+server.seed" "689777" "+server.worldsize" "3000" "+server.saveinterval" "600" "-logfile" "server.log" "-batchmode" "+server.hostname" "SERVERNAMEHERE" "+server.seed" "6834" "+server.worldsize" "4000" "+server.identity" "SERVERIDENTITYHERE" 

Needless to say, the server launches with the default unchangeable parameters.

**Comment by BattlefieldDuck** [comment]
WindowsGSM v1 created a server.cfg which contains the startup parameters. You may edit the server.cfg.

**Comment by QuintonAjStevens** [comment]
Thank you. I was able to adjust this. Sorry for that! I couldn't find anything on it and I'm new to this.
