### ISSUE TITLE
Console not working for 7 Days to Die

### ISSUE THREAD

**Issue by mikl0s** [WindowsGSM/WindowsGSM#119]
**Describe the bug**
The server console does not show when embedded or when toggeling it. Closing the toggeled console closes the server instance.

**To Reproduce**
1. Install 7 Days to Start
2. Start with or without embedded console
3. Try to access server console

**Expected behavior**
Embedded og toggled console should show text.

**Desktop (please complete the following information):**
 - Windows 10 21H2
 - WindowsGSM latest

**Additional context**
In the dashboard the active player count isn't showing for 7 Days to Die, but it might be related to the console issue so I have not made a seperate issue for this (yet). I've also tried raising these issues on Discord without luck.

**Comment by BattlefieldDuck** [comment]
Closing the toggled console will only hide the server console, you can display the console again by clicking the toggle console again.

I confirmed the 7D2D server doesn't work on the embed console now, please disable it thank you.

The active player count doesn't support the 7D2D server currently.

**Comment by mikl0s** [comment]
Confirmed that toggling console off/on will show the console in the popup window. Closing the popup window on the X will terminate the server instance - to "close" the console window you have to toggle it off.
