### ISSUE TITLE
Crashing (Maybe on server restart)

### ISSUE THREAD

**Issue by IntensityGit** [WindowsGSM/WindowsGSM#12]
**Describe the bug**
I'm not sure how to reproduce but the program seems to be crashing I think it's something to do with the automated server restarts that I have but I can't be sure as it happens while I'm asleep.

**Desktop (please complete the following information):**
WindowsGSM version: 1.10.1
Windows Version: Windows Server 2012 r2

**Comment by BattlefieldDuck** [comment]
Can you tell me what game servers you had installed?

**Comment by IntensityGit** [comment]
3 Servers all CSGO

**Comment by IntensityGit** [comment]
Crashed again just now (3 am UK time) exactly when the servers are set to restart so safe to assume it is the server restarts that are causing it. (I should say I started using the crontab feature included with windowsgsm, restarting via a plugin worked fine)

**Comment by BattlefieldDuck** [comment]
@IntensityGit Please update to v1.11.0 thanks.
When the windowsgsm crashed, it will pop out a crash message box.
Please screenshot the crash message box and send it to here if the crash happens.

**Comment by IntensityGit** [comment]
I updated to it before the restart there was no message box I don't believe, I'll check again tonight.

**Comment by IntensityGit** [comment]
So the GSM crashed again there was definitely no error box... but it did crash during the day as well but I didn't realise there was an error box until I had closed the program and the error box disappeared. Might be worth making it log to a file instead of just a box? But yeah the crash during the night I'm assuming has something to do with the restart crontab just like I say there was no error that came with it.

**Comment by BattlefieldDuck** [comment]
Seems it is related to .NET reason, as you are using Windows Server 2012 so the .NET maybe be not version 4.7.2.

Please install .NET Framework 4.7.2 https://dotnet.microsoft.com/download/dotnet-framework/net472 and restart the windows server to see the crash issue still exist.

Recently, I received a client report about an unknown crashing issue, after he installed .NET Framework 4.7.2, the crashing issue was fixed.

Please give it a try and thanks for your report.

**Comment by IntensityGit** [comment]
I already have .NET 4.7.2. Any other ideas?
![z3mee](https://user-images.githubusercontent.com/58851674/74596364-2e1ff300-5046-11ea-9384-3b0ca81dc8ee.png)

**Comment by BattlefieldDuck** [comment]
can you send the content of your WindowsGSM.cfg? thanks.

**Comment by IntensityGit** [comment]
`servergame="Counter-Strike: Global Offensive Dedicated Server"
servername="Intensity | Mirage Only"
serverip="37.59.1.153"
serverport="27015"
servermap="de_mirage"
servermaxplayer="26"
servergslt="8A2FB8098095A46AF3271341EDE92CE6"
serverparam="-insecure -usercon +ip 37.59.1.153 -console +mapgroup mirageonly +game_mode 1 +game_type 0 -nobots"

autorestart="1"
autostart="1"
autoupdate="1"
updateonstart="0"

discordalert="1"
discordwebhook="https://discordapp.com/api/webhooks/637000249310707724/fstlDaHoIghMsvXskiFk2EKGOuK8Vy5A1MY6EgqRPBlqZQjpPKEabthmN_a7DlSc2s6q"
crontabformat="0 3 * * *"
restartcrontab="1"
embedconsole="1"
`

**Comment by IntensityGit** [comment]
servergame="Counter-Strike: Global Offensive Dedicated Server"
servername="Intensity | Mirage Only"
serverip="37.59.1.153"
serverport="27015"
servermap="de_mirage"
servermaxplayer="26"
servergslt=""
serverparam="-insecure -usercon +ip 37.59.1.153 -console +mapgroup mirageonly +game_mode 1 +game_type 0 -nobots"

autorestart="1"
autostart="1"
autoupdate="1"
updateonstart="0"

discordalert="1"
discordwebhook="https://discordapp.com/api/webhooks/637000249310707724/fstlDaHoIghMsvXskiFk2EKGOuK8Vy5A1MY6EgqRPBlqZQjpPKEabthmN_a7DlSc2s6q"
crontabformat="0 3 * * *"
restartcrontab="1"
embedconsole="1"

**Comment by IntensityGit** [comment]
servergame="Counter-Strike: Global Offensive Dedicated Server"
servername="Intensity | Mirage Only"
serverip="37.59.1.153"
serverport="27015"
servermap="de_mirage"
servermaxplayer="26"
servergslt=""
serverparam="-insecure -usercon +ip 37.59.1.153 -console +mapgroup mirageonly +game_mode 1 +game_type 0 -nobots"

autorestart="1"
autostart="1"
autoupdate="1"
updateonstart="0"

discordalert="1"
discordwebhook=""
crontabformat="0 3 * * *"
restartcrontab="1"
embedconsole="1"

**Comment by BattlefieldDuck** [comment]
thanks, but I just tested the server with your config. No issue at all.

I think you may try set `crontabformat="* * * * *"` ( every minute )
to test the restart crontab function is it the crashing issue thanks.

**Comment by IntensityGit** [comment]
I don't believe this is the same crash as the one I initially reported but here is a crash log.
![z5p5t](https://user-images.githubusercontent.com/58851674/74598399-bfa05c80-5068-11ea-8d48-d0ec3d5e3350.png)

**Comment by BattlefieldDuck** [comment]
v1.11.1 should be fixed it. If you figure out some issue, feel free to report thanks :D

**Comment by IntensityGit** [comment]
Doesn't seem to have fixed it. Crashed again last night with no error box.
