### ISSUE TITLE
One click Sourcemod install 

### ISSUE THREAD

**Issue by ItsCEED** [WindowsGSM/WindowsGSM#13]
The title is pretty self-explanatory, would be great addition!

**Comment by EndreEndi** [comment]
Also sourcemod updater? ifthey're still updating it?!

**Comment by crashzk** [comment]
> Também atualizador sourcemod? se eles ainda estão atualizando ?!

Yes, it would be good, they are constantly updating SourceMod.

I recommend including the installation of Metamod as well.

**Comment by BattlefieldDuck** [comment]
WindowsGSM v1.14.0 supports one-click installation SourceMod and MetaMod.
Tools -> Install Addons -> SourceMod + MetaMod

![installAddons](https://user-images.githubusercontent.com/29337428/75846744-30d96100-5e18-11ea-9e09-222a9e4fb3a4.png)
