### ISSUE TITLE
Still crashing on restart

### ISSUE THREAD

**Issue by IntensityGit** [WindowsGSM/WindowsGSM#14]
The crashing on restart issue is still happening and I'm convinced it's something to do with the WindowsGSM crontabs because restarting the server using a plugin instead works fine. There was no error box on crash

**Comment by BattlefieldDuck** [comment]
Please update to v1.12.0, it has fixed a crash issue on server stop. Please see if the issue still exist thanks.

**Comment by IntensityGit** [comment]
It crashed again last night with no error message. It seems to only be when I have the restart crontabs on all 3 servers, I can have it on 1 and use a plugin for the other 2 but having windows GSM restart all 3 crashes. It doesn't seem to happen when I restart them all every minute so maybe only when they've got players or have been online for a long period of time? I'm not sure.

**Comment by BattlefieldDuck** [comment]
please check the logs folder, do you see a crash log - CRASH_yyyyMMdd.log?

**Comment by IntensityGit** [comment]
No only the standard logs
![zfzwm](https://user-images.githubusercontent.com/58851674/75066167-3bbff780-54e2-11ea-9418-287bd48804c1.png)

**Comment by BattlefieldDuck** [comment]
that is weird, did you enable start on login feature?

**Comment by IntensityGit** [comment]
I did yes.

**Comment by BattlefieldDuck** [comment]
Can you please disable it for a while and see if the crash still exist? I believe wgsm didn't crash but something force wgsm to close. Thanks.

**Comment by IntensityGit** [comment]
Sure I'll let you know what happens soon.

**Comment by IntensityGit** [comment]
Crashed again tonight not sure if it'll help but here's a screenshot of what happens.
![zvkuz](https://user-images.githubusercontent.com/58851674/75085510-0affb280-5522-11ea-9b90-855457e63fb7.png)

**Comment by IntensityGit** [comment]
Crashed again tonight not sure if it'll help but here's a screenshot of what happens.
![z363f](https://user-images.githubusercontent.com/58851674/75085550-66ca3b80-5522-11ea-947b-97b1539e7bf0.png)

**Comment by BattlefieldDuck** [comment]
thanks for the report, I will look into it, please disable restart crontab for a while to see and see if wgsm still crashing.

**Comment by IntensityGit** [comment]
It doesn't crash with 0-1 server using the restart crontab but using the restart crontab for multiple servers it crashes

**Comment by IntensityGit** [comment]
Here's another crash log.
[CRASH_20200224.log](https://github.com/WindowsGSM/WindowsGSM/files/4245757/CRASH_20200224.log)

**Comment by BattlefieldDuck** [comment]
I will fix this in next release
thx for the report!

**Comment by IntensityGit** [comment]
No problem. I've also noticed that auto update doesn't seem to work there was an update last night and the server didn't stop to update at all.

**Comment by BattlefieldDuck** [comment]
can you send the windowsgsm log of the day that csgo update? thanks

**Comment by IntensityGit** [comment]
Sure here, as you can see I had to stop and use update on start myself instead of auto update.
[L20200225.log](https://github.com/WindowsGSM/WindowsGSM/files/4250891/L20200225.log)

**Comment by BattlefieldDuck** [comment]
thanks for that, I will look into it.

**Comment by IntensityGit** [comment]
So I've left auto restart off for a couple of days and it hasn't crashed at all I'll turn it back on to auto restart tonight and see if it crashes and let you know.

**Comment by IntensityGit** [comment]
Auto restarted tonight perfectly fine although I did just restart the servers a couple hours ago (2 am) 3am being when they auto restart to update to the latest WGSM version so I'll see if they crash tomorrow night.

**Comment by IntensityGit** [comment]
Issue seems to be fixed WGSM didn't crash again tonight on version 1.13.0

**Comment by BattlefieldDuck** [comment]
nice~. Thanks for the testing @IntensityGit! Please join our discord group if you have a discord account https://discord.gg/bGc7t2R.
