### ISSUE TITLE
Can you add TeamSpeak 3 Server?

### ISSUE THREAD

**Issue by EndreEndi** [WindowsGSM/WindowsGSM#15]
as in title, please, can you add it?

**Comment by BattlefieldDuck** [comment]
thanks for the suggestion, I will add it as soon as possible!

**Comment by crashzk** [comment]
It would also be good to include support for Ventrilo.

**Comment by EndreEndi** [comment]
I hope it will be added soon:)

**Comment by EndreEndi** [comment]
bump:)

**Comment by Alauraa** [comment]
> I hope it will be added soon:)

As well as mumble if your planning on adding everything that is a VOIP for today's services.

**Comment by Alauraa** [comment]
> It would also be good to include support for Ventrilo.

As well as mumble if your planning on adding everything that is a VOIP for today's services.

**Comment by EndreEndi** [comment]
Up
