### ISSUE TITLE
Can you please add Insurgency Sandstorm

### ISSUE THREAD

**Issue by TheFuchs** [WindowsGSM/WindowsGSM#22]
Would it be possible to add Insurgency Sandstorm, , or is it planned anyways?

Could it be possible if we can have some sort of putting in a appid from steam for custom games/server?
Like it is with steamcmd gui?

BTW glad your tool exists beside LinuxGSM which[Linux] i'm not familiar with!
THX Fuchs

**Comment by BattlefieldDuck** [comment]
will support Insurgency Sandstorm server in the future for sure.

It is impossible to add custom game server because every game server is unique, WindowsGSM has additional features to manage the server.

Also thanks for using WindowsGSM!

**Comment by TheFuchs** [comment]
Thank you very much fo the fast answering !

Keep up the good work and stay healthy !

THX Fuchs

**Comment by TheFuchs** [comment]
Thank you very much for adding Sandstorm!!!
