### ISSUE TITLE
Cancelling an install doesn't actually stop the download

### ISSUE THREAD

**Issue by Deathreus** [WindowsGSM/WindowsGSM#26]
While the program is installing a server, if you click to cancel the process it doesn't actually kill the SteamCMD that's performing work, as proven by attempting to install again reporting that it can't access the folder and not being able to delete the folder manually

 - OS: Windows 1903
 - Version 1.15.1

**Comment by BattlefieldDuck** [comment]
Cancel installation function was removed in v1.16.0.
