### ISSUE TITLE
Rust dedicated not receiving parameters/Stopping after downloading custom map

### ISSUE THREAD

**Issue by lucblack** [WindowsGSM/WindowsGSM#48]
**Describe the bug**
Issue 1- <s>Server is not getting passed special parameters.</s> (Windowsgsm default to the config inside the server folder instead of what's shown in the gui)
Issue 2- Custom map making server hang up
https://cdn.discordapp.com/attachments/529123862596812801/729022487865852024/unknown.png

**Stuff inside params:**
+levelurl https://www.dropbox.com/XXXXXXXXXXXXXXXXXXXXXXX.map?dl=1 +server.description "potato +server.port 27020 +rcon.port 27021 +rcon.password "XXXXXXXXXXXXXXX" +server.identity "XXXXXX" -logfile "log.txt" +server.hostname "XXXXXXXX+server.maxplayers 100

**To Reproduce**
1. Try to add parameters under "Server start param" and run the server to see they won't be passed down
2. Try adding a custom map url and run the server to have it stop after downloading it

**Expected behavior**
Server starts up fine (which it does when pasting the same params and running RustDedicated.exe using a batch file)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by BattlefieldDuck** [comment]
Can you check the server.cfg in the Rust serverfiles? WindowsGSM loads the server.cfg for the start param since the start param is too long in the rust server. You may need to edit the server.cfg instead of adding param in WindowsGSM.cfg. 

Thanks for the report. 👍
