### ISSUE TITLE
Server crash on stop; Always restarts it

### ISSUE THREAD

**Issue by Deathreus** [WindowsGSM/WindowsGSM#5]
**Describe the bug**
If you press `Stop` and in the process of the server shutting down it crashes, then the program will start it up again

**Expected behavior**
Stopping actually stops the server regardless of what happens

**Desktop:**
 - OS: Window 10
 - Version 1903

**Additional context**
Some specific plugins cause a crash on exit, I think it's a thread issue, at any rate one of my servers has always crashed on exit even without third-party items running on it.

**Comment by BattlefieldDuck** [comment]
Sorry to tell you that I cannot reproduce the bug that you had mentioned. The crash detection should be stopped when the button `STOP` is pressed. Can you tell me what is your current game server? Notice that v1.7.0 is the latest version.

**Comment by Deathreus** [comment]
I'm using what was downloaded when cloning

**Comment by BattlefieldDuck** [comment]
![2019-12-21 (3)](https://user-images.githubusercontent.com/29337428/71639655-39e17100-2cb5-11ea-9777-d7905abf0983.png)
If auto-restart is on, the crash detection will enable, once the server is crashed or closed, the server will auto restart. You may disable it in WindowsGSM.cfg.

**Comment by Deathreus** [comment]
It seems to have resolved itself ¯\_(ツ)_/¯
