### ISSUE TITLE
WindowGSM console turned into an actual console

### ISSUE THREAD

**Issue by Deathreus** [WindowsGSM/WindowsGSM#9]
I propose the console of the WindowGSM client be used to display the output of the server you have selected. There's already hooks for when the selection changes, so swapping console text can happen in there. A simple fixed size FIFO array can be used to store the messages per console cleanly, and with very little memory usage; As a new element comes in, the first one is popped off the memory. 

I was not going to create a pull request for this as it's had very little testing (Read: just starting up a minecraft and TF2 server and shutting it down), but you can see what I've done [here](https://github.com/Deathreus/WindowsGSM/commit/7a5c724113de183960c3e33a0cbac88cff850c25)

**Comment by BattlefieldDuck** [comment]
That's a good idea. If RedirectStandardOutput, then the game server console windows become completely useless, and it should use RedirectStandardInput too.

I have this redirect output idea before, I had tested redirect output on the steamcmd.exe but it doesn't work well (some delay) so I give up and created a toggle console button to toggle the game server console.

**Comment by BattlefieldDuck** [comment]
I will work on it in a few days
